= The Hallmark Pipeline <sec-hallmark>

We now describe the architecture of Hallmark as a concrete system,
tying together the components introduced in the preceding sections.

== Overview

Hallmark is a MetaRocq plugin that, given one or more inductive type
definitions, produces a Prolog source file ready to be loaded into
an interpreter such as SWI-Prolog.

The pipeline has three stages (@fig-pipeline):

#figure(
  table(
    columns: 3,
    align: (center, center, center),
    table.header[*Stage*][*Input*][*Output*],
    [Quoting],
    [Rocq inductive definition],
    [MetaRocq AST],
    [Translation],
    [MetaRocq AST],
    [Internal clause representation],
    [Emission],
    [Internal clauses],
    [Prolog source text],
  ),
  caption: [The three stages of the Hallmark pipeline.],
) <fig-pipeline>

== Stage 1: Quoting

The user writes an inductive definition in standard Rocq and invokes
Hallmark via the TemplateMonad:

```coq
MetaRocq Run (tmQuoteRec "allowed").
```

This produces a value of type `program`, a list of global declarations
that includes the inductive type and all its dependencies.
The inductive entry contains, among other things:

- The name and arity of the type (e.g. `allowed : user -> resource -> Prop`).
- The list of constructors, each with its full type.
- Universe constraints (which we discard for clause generation, as
  Prolog has no universe hierarchy).

== Stage 2: Translation

The translation walks each constructor's type — a nested sequence
of dependent products — and classifies every binding into one of
three categories (a full reference of the AST constructors involved
is given in @appendix-ast):

- *Index variable*: a data argument that appears in the head
  (e.g. the `user` or `resource` in `allowed u r`).
- *Premise*: an anonymous argument whose type is an application of an
  inductive predicate, which becomes a body atom.
- *CLP(FD) constraint*: an anonymous argument whose head predicate
  appears in the CLP(FD) operator table (see @sec-clp), emitted as a
  `clpfd_check(L op R)` goal rather than a plain atom.
- *Erased argument*: a type-level or proof-level argument that carries
  no computational content and is dropped.

For the `delegate` constructor:

```coq
delegate : forall u v r,
  manager_of u v -> allowed v r -> allowed u r
```

the translation identifies the bindings shown in
@fig-delegate-analysis:

#figure(
  table(
    columns: 3,
    align: (left, left, left),
    table.header[*Binding*][*Category*][*Role in clause*],
    [`u : user`],       [Index variable], [Head: `allowed(U, R)`],
    [`v : user`],       [Index variable], [Body variable],
    [`r : resource`],   [Index variable], [Head: `allowed(U, R)`],
    [`_ : manager_of u v`], [Premise],    [Body: `manager_of(U, V)`],
    [`_ : allowed v r`],    [Premise],    [Body: `allowed(V, R)`],
  ),
  caption: [Constructor analysis for `delegate`.],
) <fig-delegate-analysis>

The output is an internal representation of the clause:

$ "manager_of"(u, v) and "allowed"(v, r) arrow.r.double "allowed"(u, r) $

=== Nullary Constructors

A special case arises when a constructor carries no arguments at all.
Consider the enum-style inductive:

```coq
Inductive user := admin | alice | bob.
```

Each constructor has type `user` with no quantified variables.
After translation the conclusion would be `user()` — an atom applied
to an empty argument list, which is not valid Prolog syntax.
The emitter detects this pattern (a head with no arguments) and
injects the constructor name as an atom argument instead:

```prolog
user(admin).
user(alice).
user(bob).
```

The resulting facts serve as an enumeration of the type's inhabitants,
and downstream clauses can pattern-match on them in the normal way.

== Stage 3: Emission

The emitter serializes each internal clause into Prolog syntax:

- Predicate names are transliterated to lowercase atoms.
- Variables are capitalized.
- Premises are joined with `,` to form the clause body.
- A `rule(ConstructorName)` goal is inserted as the first atom
  of every non-fact clause body, tagging the rule with the Rocq
  constructor that produced it.
  Clauses with no premises are emitted as bare Prolog facts;
  their constructor names are stored in `ctor_witness/4` declarations
  emitted alongside the clauses for proof reconstruction.

For the `allowed` example, the complete output is:

```prolog
% Generated by Hallmark from inductive type: allowed
rule(_).
allowed(admin, R).
allowed(U, public_doc).
allowed(U, R) :- rule(delegate), manager_of(U, V), allowed(V, R).
ctor_witness(admin_all, allowed(admin, R), [], app(admin_all, [R])).
ctor_witness(read_public, allowed(U, public_doc), [], app(read_public, [U])).
ctor_witness(delegate, allowed(U, R), [manager_of(U, V), allowed(V, R)],
             app(delegate, [U, V, R, pf(0), pf(1)])).
```

The `rule/1` tag carries no computational cost — it always
succeeds — but it makes every non-fact clause self-identifying.
The `ctor_witness/4` declarations serve the complementary role for
facts: they record the constructor name, head pattern, body atoms,
and Rocq term template used during proof reconstruction.
The next section exploits both mechanisms.

== Trusted External Predicates

Most rule sets depend on predicates whose facts are not part of the
compiled module — they are supplied at runtime by the caller.
`manager_of` and `age_of` are typical examples: the Rocq definition
uses them as premises, but their contents are domain-specific and
must remain editable without recompiling the rules.

Hallmark provides a lightweight declaration mechanism for this purpose.
The user writes a `Definition` whose body is `True`:

```coq
Definition manager_of (u v : user) : Prop := True.
```

The body `True` carries no logical content; it is a signal to the
pipeline that `manager_of` is an external placeholder rather than
a compiled predicate.

During quoting the pipeline detects this pattern — a constant whose
body reduces to a sequence of lambda binders wrapping `True` — and
records its name and arity.
The emitter then produces two declarations for each trusted predicate:

```prolog
:- dynamic manager_of/2.
trusted_pred(manager_of).
```

The `:- dynamic` directive tells SWI-Prolog that facts for
`manager_of` will be asserted at runtime.
The `trusted_pred/1` marker is read by the proof witness system:
when `witness/2` encounters a resolved goal whose predicate is
trusted, it emits `app('I', [])` — the Rocq term for the unique
proof of `True` — rather than attempting to reconstruct a
derivation tree.
This closes the round-trip: external facts are treated as opaque
axioms whose Rocq counterpart is the trivially true proposition.

== Running the Generated Engine

Once the Prolog file is produced, using it is straightforward.
A fact base is supplied for the auxiliary predicates
(here, `manager_of`), and queries are posed as usual:

```prolog
manager_of(eve, admin).

?- allowed(eve, secret_report).
true.
```

Prolog chains backward through `delegate`, resolves `manager_of` and
`allowed` for the administrator, and confirms the query.
The reasoning path follows exactly the inference rules defined in Rocq.
