= Proof Witnesses <sec-witnesses>

When a Prolog engine resolves a query against Hallmark-generated
clauses, it does more than produce a yes-or-no answer.
The resolution process _is_ a proof search, and every step
corresponds to the application of a rule from the original Rocq
definition.
This section shows how to capture that process and reconstruct
a formal proof term that Rocq can independently verify.

== Resolution Traces as Derivation Trees

Recall from @sec-prolog that Prolog proves a goal by backward
chaining: it selects a clause whose head matches the goal,
unifies the arguments, and recursively proves each subgoal in the
clause body.
The sequence of clause applications forms a tree.

- The _root_ is the original query.
- Each _internal node_ records which clause was applied and what
  substitution was produced.
- The _children_ of a node are the subgoals generated by the
  clause body.
- A _leaf_ is a fact (a clause with no body): the subgoal is
  proved directly.

This tree is the _SLD resolution trace_ — a complete record of
the engine's reasoning.

== The Structural Correspondence

Because Hallmark compiles each Rocq constructor to exactly one
Prolog clause, the resolution trace maps directly onto a Rocq
proof term:

#figure(
  table(
    columns: 2,
    align: (left, left),
    table.header[*Prolog (resolution trace)*][*Rocq (proof term)*],
    [Clause application],
    [Constructor application],
    [Resolved atom (clause head)],
    [Conclusion of the constructor],
    [Body atoms (subgoals)],
    [Premises of the constructor],
    [Fact (clause with empty body)],
    [Constructor with no premises],
  ),
  caption: [Correspondence between resolution traces and proof terms.],
) <fig-trace-correspondence>

Each node in the trace identifies _which_ clause was used and
_what_ arguments were bound.
Since the clause-to-constructor mapping is one-to-one (and known
to the translator), these two pieces of information suffice to
reconstruct the Rocq term.

== A Concrete Example

Consider the query `allowed(eve, secret_report)` with the
following fact base:

```prolog
manager_of(eve, admin).
```

The resolution trace proceeds as follows:

+ *Goal:* `allowed(eve, secret_report)`.
  Resolved by the clause from `delegate`:
  `allowed(U, R) :- manager_of(U, V), allowed(V, R)`.
  Substitution: `U = eve`, `R = secret_report`.

+ *Subgoal 1:* `manager_of(eve, V)`.
  Resolved by the fact `manager_of(eve, admin)`.
  Substitution: `V = admin`.

+ *Subgoal 2:* `allowed(admin, secret_report)`.
  Resolved by the clause from `admin_all`:
  `allowed(admin, R)`.
  Substitution: `R = secret_report`.

The corresponding Rocq proof term is:

```coq
delegate eve admin secret_report
  manager_of_eve_admin
  (admin_all secret_report)
```

The tree structure is identical: `delegate` requires two premises
(a proof of `manager_of` and a proof of `allowed`), and the trace
supplies both by resolving the corresponding subgoals.

== Self-Documenting Clauses

A resolution trace is only useful if each step identifies
_which constructor_ was applied.
Prolog's `clause/3` can return a clause reference, but this
is opaque and implementation-dependent.

Hallmark uses two mechanisms, one per clause shape.
For clauses with premises, it inserts the constructor name as the
first body goal via a `rule/1` tag.
For fact clauses (no premises), it emits a `ctor_witness/4`
declaration that records the constructor name alongside the head
pattern.

```prolog
% Generated by Hallmark from inductive type: allowed
allowed(admin, R).
allowed(U, public_doc).
allowed(U, R) :-
    rule(delegate),
    manager_of(U, V),
    allowed(V, R).
ctor_witness(admin_all, allowed(admin, R), [], app(admin_all, [R])).
ctor_witness(read_public, allowed(U, public_doc), [], app(read_public, [U])).
ctor_witness(delegate, allowed(U, R), [manager_of(U, V), allowed(V, R)],
             app(delegate, [U, V, R, pf(0), pf(1)])).
```

The `rule/1` predicate is trivial — it always succeeds:

```prolog
rule(_).
```

Its sole purpose is to tag each non-fact clause body with the Rocq
constructor name.
The `ctor_witness/4` declarations serve the same role for facts:
when the interpreter resolves a bare Prolog fact, it queries
`ctor_witness` to recover the constructor name and the Rocq term
template needed for proof reconstruction.
Together, the two mechanisms ensure that every compiled clause is
self-identifying and the constructor name travels from the Rocq
definition all the way to the execution trace.

== Capturing the Trace

With constructor names embedded in the clauses, a meta-interpreter
can record the proof tree directly:

```prolog
why(Goal, proof(Goal, by(Rule, []))) :-
    clause(Goal, true), !,
    (ctor_witness(Rule, Goal, [], _) -> true ; Rule = fact).
why(Goal, proof(Goal, by(Rule, SubProofs))) :-
    clause(Goal, Body),
    body_rule(Body, Rule, Rest),
    why_body(Rest, SubProofs).

body_rule((rule(R), Rest), R, Rest).
body_rule(rule(R), R, true).

why_body(true, []).
why_body((G, Rest), [P | Ps]) :-
    !,
    why(G, P),
    why_body(Rest, Ps).
why_body(G, [P]) :-
    G \= true, G \= (_, _),
    why(G, P).
```

The `body_rule` helper peels off the `rule(Name)` tag from
the clause body, and the rest of the interpreter collects
subproofs as before.
For bare facts, the interpreter queries `ctor_witness` to recover
the constructor name; goals with no matching `ctor_witness` entry
are external facts tagged `fact`.
The result is a tree where each node carries the constructor name:

```prolog
?- why(allowed(eve, secret_report), P).
P = proof(allowed(eve, secret_report),
      by(delegate, [
        proof(manager_of(eve, admin), by(fact, [])),
        proof(allowed(admin, secret_report),
          by(admin_all, []))
      ])).
```

Each `by(Name, ...)` node maps directly to a constructor
application in Rocq — the correspondence is explicit, not
inferred from clause references.

This meta-interpreter is a static library bundled with the Hallmark
binary and appended verbatim to every generated Prolog file.
It is generic: it operates on any Hallmark output by relying on the
`rule/1` tags and `ctor_witness/4` declarations that the emitter
produces.
Loading the generated file therefore gives immediate access to both
the rules engine and the proof-capturing interpreter.

== Reconstructing the Rocq Term

Given the proof tree and the clause-to-constructor mapping (which
the translator maintains), the reconstruction proceeds bottom-up:

+ For each leaf `fact(Goal)`, look up the corresponding
  constructor (a fact maps to a constructor with no premises) and
  apply it to the arguments extracted from the substitution.

+ For each internal node `node(Goal, Subproofs)`, look up the
  constructor and apply it to:
  - The _data arguments_ from the substitution (the index
    variables).
  - The _proof arguments_ obtained by recursively reconstructing
    each subproof.

The output is a Rocq term of the inductive type — a fully
explicit proof object.

== Certification by Type-Checking

The reconstructed term is not taken on trust.
It is fed back into Rocq, where the type-checker verifies that it
has the expected type.

```coq
Check (delegate eve admin secret_report
         manager_of_eve_admin
         (admin_all secret_report)
       : allowed eve secret_report).
```

If the term type-checks, the proof is valid: the Prolog engine's
answer is certified by an independent verifier.
If it does not, an error in the translation or the meta-interpreter
has been detected — a safety net that closes the trust gap.

This _round-trip_ — Rocq definition, Prolog execution,
trace capture, term reconstruction, Rocq verification — is the
strongest guarantee Hallmark can offer.
The Prolog engine is untrusted; the proof it produces is
independently checked.

== Practical Applications

Proof witnesses serve several purposes beyond formal certification:

- *Audit trails.*
  In a compliance-sensitive domain (finance, healthcare, access
  control), every decision must be explainable.
  The proof tree records _which rules fired_ and _in what order_,
  providing a complete audit trail that can be archived and
  reviewed.

- *Explainability.*
  The proof term can be rendered as a human-readable derivation:
  "Access was granted because Eve manages Admin, who has direct
  access to the resource."
  Unlike black-box systems, the explanation is structurally tied
  to the inference rules — it cannot be misleading.

- *Formal certificates.*
  The proof term can be exported and verified by a third party
  who holds only the inductive definition — no access to the
  fact base or the Prolog engine is needed.
  This is analogous to _proof-carrying code_: the producer does
  the expensive work (proof search), and the consumer does the
  cheap work (type-checking).

- *Regression testing.*
  Archived proof terms from previous runs can be re-checked
  against an updated rule set.
  If a rule change invalidates a previously valid derivation,
  the type-checker detects it immediately.
