= The Hallmark Pipeline <sec-hallmark>

We now describe the architecture of Hallmark as a concrete system,
tying together the components introduced in the preceding sections.

== Overview

Hallmark is a MetaRocq plugin that, given one or more inductive type
definitions, produces a Prolog source file ready to be loaded into
an interpreter such as SWI-Prolog.

The pipeline has three stages (@fig-pipeline):

#figure(
  table(
    columns: 3,
    align: (center, center, center),
    table.header[*Stage*][*Input*][*Output*],
    [Quoting],
    [Rocq inductive definition],
    [MetaRocq AST],
    [Translation],
    [MetaRocq AST],
    [Internal clause representation],
    [Emission],
    [Internal clauses],
    [Prolog source text],
  ),
  caption: [The three stages of the Hallmark pipeline.],
) <fig-pipeline>

== Stage 1: Quoting

The user writes an inductive definition in standard Rocq and invokes
Hallmark via the TemplateMonad:

```coq
MetaRocq Run (tmQuoteRec "allowed").
```

This produces a value of type `program`, a list of global declarations
that includes the inductive type and all its dependencies.
The inductive entry contains, among other things:

- The name and arity of the type (e.g. `allowed : user -> resource -> Prop`).
- The list of constructors, each with its full type.
- Universe constraints (which we discard for clause generation, as
  Prolog has no universe hierarchy).

== Stage 2: Translation

The translation walks each constructor's type — a nested sequence
of dependent products — and classifies every binding into one of
three categories (a full reference of the AST constructors involved
is given in @appendix-ast):

- *Index variable*: a data argument that appears in the head
  (e.g. the `user` or `resource` in `allowed u r`).
- *Premise*: an argument whose type is an application of an inductive
  predicate, which becomes a body atom.
- *Erased argument*: a type-level or proof-level argument that carries
  no computational content and is dropped.

For the `delegate` constructor:

```coq
delegate : forall u v r,
  manager_of u v -> allowed v r -> allowed u r
```

the translation identifies the bindings shown in
@fig-delegate-analysis:

#figure(
  table(
    columns: 3,
    align: (left, left, left),
    table.header[*Binding*][*Category*][*Role in clause*],
    [`u : user`],       [Index variable], [Head: `allowed(U, R)`],
    [`v : user`],       [Index variable], [Body variable],
    [`r : resource`],   [Index variable], [Head: `allowed(U, R)`],
    [`_ : manager_of u v`], [Premise],    [Body: `manager_of(U, V)`],
    [`_ : allowed v r`],    [Premise],    [Body: `allowed(V, R)`],
  ),
  caption: [Constructor analysis for `delegate`.],
) <fig-delegate-analysis>

The output is an internal representation of the clause:

$ "manager_of"(u, v) and "allowed"(v, r) arrow.r.double "allowed"(u, r) $

== Stage 3: Emission

The emitter serializes each internal clause into Prolog syntax:

- Predicate names are transliterated to lowercase atoms.
- Variables are capitalized.
- Premises are joined with `,` to form the clause body.
- Facts (clauses with no premises) are emitted without `:-`.

For the `allowed` example, the complete output is:

```prolog
% Generated by Hallmark from inductive type: allowed
allowed(admin, R).
allowed(U, public_doc).
allowed(U, R) :- manager_of(U, V), allowed(V, R).
```

This file is valid SWI-Prolog.
Loading it and posing queries immediately yields a backward-chaining
inference engine whose rules are exactly those specified in the Rocq
definition.

== Running the Generated Engine

Once the Prolog file is produced, using it is straightforward.
A fact base is supplied for the auxiliary predicates
(here, `manager_of`), and queries are posed as usual:

```prolog
manager_of(eve, admin).

?- allowed(eve, secret_report).
true.
```

Prolog chains backward through `delegate`, resolves `manager_of` and
`allowed` for the administrator, and confirms the query.
The reasoning path follows exactly the inference rules defined in Rocq.
