= Proof Witnesses <sec-witnesses>

When a Prolog engine resolves a query against Hallmark-generated
clauses, it does more than produce a yes-or-no answer.
The resolution process _is_ a proof search, and every step
corresponds to the application of a rule from the original Rocq
definition.
This section shows how to capture that process and reconstruct
a formal proof term that Rocq can independently verify.

== Resolution Traces as Derivation Trees

Recall from @sec-prolog that Prolog proves a goal by backward
chaining: it selects a clause whose head matches the goal,
unifies the arguments, and recursively proves each subgoal in the
clause body.
The sequence of clause applications forms a tree.

- The _root_ is the original query.
- Each _internal node_ records which clause was applied and what
  substitution was produced.
- The _children_ of a node are the subgoals generated by the
  clause body.
- A _leaf_ is a fact (a clause with no body): the subgoal is
  proved directly.

This tree is the _SLD resolution trace_ — a complete record of
the engine's reasoning.

== The Structural Correspondence

Because Hallmark compiles each Rocq constructor to exactly one
Prolog clause, the resolution trace maps directly onto a Rocq
proof term:

#figure(
  table(
    columns: 2,
    align: (left, left),
    table.header[*Prolog (resolution trace)*][*Rocq (proof term)*],
    [Clause application],
    [Constructor application],
    [Resolved atom (clause head)],
    [Conclusion of the constructor],
    [Body atoms (subgoals)],
    [Premises of the constructor],
    [Fact (clause with empty body)],
    [Constructor with no premises],
  ),
  caption: [Correspondence between resolution traces and proof terms.],
) <fig-trace-correspondence>

Each node in the trace identifies _which_ clause was used and
_what_ arguments were bound.
Since the clause-to-constructor mapping is one-to-one (and known
to the translator), these two pieces of information suffice to
reconstruct the Rocq term.

== A Concrete Example

Consider the query `allowed(eve, secret_report)` with the
following fact base:

```prolog
manager_of(eve, admin).
```

The resolution trace proceeds as follows:

+ *Goal:* `allowed(eve, secret_report)`.
  Resolved by the clause from `delegate`:
  `allowed(U, R) :- manager_of(U, V), allowed(V, R)`.
  Substitution: `U = eve`, `R = secret_report`.

+ *Subgoal 1:* `manager_of(eve, V)`.
  Resolved by the fact `manager_of(eve, admin)`.
  Substitution: `V = admin`.

+ *Subgoal 2:* `allowed(admin, secret_report)`.
  Resolved by the clause from `admin_all`:
  `allowed(admin, R)`.
  Substitution: `R = secret_report`.

The corresponding Rocq proof term is:

```coq
delegate eve admin secret_report
  manager_of_eve_admin
  (admin_all secret_report)
```

The tree structure is identical: `delegate` requires two premises
(a proof of `manager_of` and a proof of `allowed`), and the trace
supplies both by resolving the corresponding subgoals.

== Capturing the Trace

A standard Prolog _meta-interpreter_ can be extended to record the
proof tree as it runs.
The key idea is to replace Prolog's built-in `call` with a custom
interpreter that threads a proof term alongside the computation:

```prolog
prove(Goal, fact(Goal)) :-
    clause(Goal, true).
prove(Goal, node(Goal, Subproofs)) :-
    clause(Goal, Body),
    prove_body(Body, Subproofs).

prove_body(true, []).
prove_body((G, Rest), [P | Ps]) :-
    prove(G, P),
    prove_body(Rest, Ps).
```

For each clause application, the interpreter records the head
(`Goal`) and recursively collects the proofs of the body goals
into a list.
The result is a tree of `node` and `fact` terms that mirrors the
SLD trace exactly.

Hallmark can ship a specialized meta-interpreter alongside the
generated clauses, tailored to the specific predicates and
constructor names of the compiled inductive.

== Reconstructing the Rocq Term

Given the proof tree and the clause-to-constructor mapping (which
the translator maintains), the reconstruction proceeds bottom-up:

+ For each leaf `fact(Goal)`, look up the corresponding
  constructor (a fact maps to a constructor with no premises) and
  apply it to the arguments extracted from the substitution.

+ For each internal node `node(Goal, Subproofs)`, look up the
  constructor and apply it to:
  - The _data arguments_ from the substitution (the index
    variables).
  - The _proof arguments_ obtained by recursively reconstructing
    each subproof.

The output is a Rocq term of the inductive type — a fully
explicit proof object.

== Certification by Type-Checking

The reconstructed term is not taken on trust.
It is fed back into Rocq, where the type-checker verifies that it
has the expected type.

```coq
Check (delegate eve admin secret_report
         manager_of_eve_admin
         (admin_all secret_report)
       : allowed eve secret_report).
```

If the term type-checks, the proof is valid: the Prolog engine's
answer is certified by an independent verifier.
If it does not, an error in the translation or the meta-interpreter
has been detected — a safety net that closes the trust gap.

This _round-trip_ — Rocq definition, Prolog execution,
trace capture, term reconstruction, Rocq verification — is the
strongest guarantee Hallmark can offer.
The Prolog engine is untrusted; the proof it produces is
independently checked.

== Practical Applications

Proof witnesses serve several purposes beyond formal certification:

- *Audit trails.*
  In a compliance-sensitive domain (finance, healthcare, access
  control), every decision must be explainable.
  The proof tree records _which rules fired_ and _in what order_,
  providing a complete audit trail that can be archived and
  reviewed.

- *Explainability.*
  The proof term can be rendered as a human-readable derivation:
  "Access was granted because Eve manages Admin, who has direct
  access to the resource."
  Unlike black-box systems, the explanation is structurally tied
  to the inference rules — it cannot be misleading.

- *Formal certificates.*
  The proof term can be exported and verified by a third party
  who holds only the inductive definition — no access to the
  fact base or the Prolog engine is needed.
  This is analogous to _proof-carrying code_: the producer does
  the expensive work (proof search), and the consumer does the
  cheap work (type-checking).

- *Regression testing.*
  Archived proof terms from previous runs can be re-checked
  against an updated rule set.
  If a rule change invalidates a previously valid derivation,
  the type-checker detects it immediately.
